name: Android Build

on:
  workflow_dispatch:
    inputs:
      name:
        description: "Ex: milestone name"
        default: "Mn"
        required: true

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

#    - name: Set permissions for google-services.json
#      run: chmod 644 ./app/google-services.json

      # Load google-services.json and local.properties from the secrets
    - name: Decode secrets
      env:
        GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        # LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
      run: |
        echo "$GOOGLE_SERVICES" | base64 --decode > ./app/google-services.json

    - name: Set executable permissions for gradlew
      run: chmod +x ./gradlew

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'  # Use Zulu OpenJDK
        java-version: '17'

    - name: Install dependencies
      run: ./gradlew dependencies

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: "${{ github.event.inputs.name }}-APK"
        path: app/build/outputs/apk/release/app-release.apk
